name: GitHub Actions Audit

on:
  push:
    branches:
      - main
    paths:
      - .github/**/*
  pull_request:
    paths:
      - .github/**/*

permissions: {}

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      security-events: write # required to upload SARIF results to GitHub Code Scanning
      contents: read # required to check out the repository
      actions: read # required by zizmor to read workflow runs

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
