name: Update profile cards

on:
  schedule:
    - cron: '0 0 * * 0' # Run every week on Sunday at midnight

  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build profile cards and open PR

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup credentials
        id: credentials
        uses: marcalexiei/github-actions/.github/actions/setup-github-app-user-bot@f27a68a73a799c79d7158cf4a98d7e3d5e8e23be # v1.1.0
        with:
          app-id: ${{ vars.CARD_UPDATER_APP_ID }}
          private-key: ${{ secrets.CARD_UPDATER_PRIVATE_KEY }}

      - name: Generate stats card (dark)
        uses: readme-tools/github-readme-stats-action@b4d2ef3b8051484b318d455163153b23a2b35fa2 # v1.0.0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=react
          path: profile/stats-dark.svg
          token: ${{ steps.credentials.outputs.token }}

      - name: Generate stats card (light)
        uses: readme-tools/github-readme-stats-action@b4d2ef3b8051484b318d455163153b23a2b35fa2 # v1.0.0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=default
          path: profile/stats-light.svg
          token: ${{ steps.credentials.outputs.token }}

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.credentials.outputs.token }}
          branch: update-profile-cards
          title: ${{ env.COMMIT_MESSAGE }}
          commit-message: ${{ env.COMMIT_MESSAGE }}
          body: Scheduled cards update
          author: ${{ env.AUTHOR }}
          committer: ${{ env.AUTHOR }}
          sign-commits: true
          delete-branch: true # avoid multiple PRs
        env:
          COMMIT_MESSAGE: 'feat: update README cards'
          AUTHOR: ${{ steps.credentials.outputs.bot-name }} <${{ steps.credentials.outputs.bot-email }}>

      - name: Enable auto-merge
        if: ${{ steps.create_pr.outputs.pull-request-number }} # PR might not being opened
        run: gh pr merge --squash --auto "${{ steps.create_pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.credentials.outputs.token }}
